# Generated by Django 5.1.4 on 2025-01-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=100),
        ),
    ]
